Headline page branch
SamuelTakyiBoateng/Mobile-Portfolio-Project pull request #2
Opened 2023-03-29 11:31 UTC by SamuelTakyiBoateng

add index.html (toolbar and headline of the first section add)
Style.css ( add style to the toolbar and headline)
ReadMe (Description about project)

2023-03-29 11:56 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @SamuelTakyiBoateng , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media1.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/> |

## Highlights

- [ ]... ✅ Good design
- [ ].. ✅ Green linters
- [ ].... ✅ Clean code

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 11:56 UTC, joskalenda commented on index.html
> +      <h2 class="header__logo">My Logo</h2>
- [ ] Well done @SamuelTakyiBoateng, I appreciate your work, however, the logo name you respect is the following:
- It must be an `a` tag to help the user navigate to the home page, Going "back to home" is a very common interaction for users browsing a corporate website
- I believe the `my logo` name on the figma design is just a reference to tell you, please replace this with your initials or your name even, such as the home logo of Facebook is not `my company`, it is Facebook, this to say, please use your name, your logo or your initial letters to represent the logo

2023-03-29 11:56 UTC, joskalenda commented on style.css
> +  background-repeat: no-repeat;
- [ ] Your background image is hiding the text, please fix this.
<img width="415" alt="1" src="https://user-images.githubusercontent.com/77843050/228527129-96632175-b033-4a41-9178-fbe252fa0f73.png">

2023-03-30 00:43 UTC, SamuelTakyiBoateng commented on index.html
> +      <h2 class="header__logo">My Logo</h2>
Thank you so much careful consideration and suggestion.
The prescribed changes have been made. Thanks again!

2023-03-30 00:44 UTC, SamuelTakyiBoateng commented on style.css
> +  background-repeat: no-repeat;
The background has been modified for it not to obstruct the text.
Thank🙏!

2023-03-30 00:53 UTC, Strangeal approved these changes
Hi @SamuelTakyiBoateng, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Highlights
Used GitHub flow ✅
Used linters ✅

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 02:17 UTC, merged