Mobile-Portfolio-Contact me
SamuelTakyiBoateng/Mobile-Portfolio-Project pull request #4
Opened 2023-04-06 10:39 UTC by SamuelTakyiBoateng

Modified index.html file to  include the display of the contact information
Modified style.css file to add color to the html changes.

2023-04-06 11:01 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @SamuelTakyiBoateng, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of Github flow. ✔️ 
 - Nice UI design. ✔️ 

## Aspects to improve ♻️

- [ ] Check the comments under the review.
- [ ] The design of your form is very nice and similar to the Figma template. But unfortunately, your form is not connected to the Formspree service and because of this the user cannot send you any message. Kindly follow the 'Getting started' section of the the [Formspree service](https://formspree.io/html) to make your form useful.
- [ ] As the project required, the user cannot submit the form if any of the input fields are empty. Please, make all of them required so the user cannot send you a message missing one or more information.
- [ ] Also, the name and message input fields should have a limit of characters of 30 and 500 characters. Please implement these limits to follow the project requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 00:36 UTC, SamuelTakyiBoateng commented
Thanks for the meticulous assessment of my project and constructive suggestion.
Please,  the form has been connected to freespace service and the form validation instruction for input field limit characters limits of 30 and 500 have been updated. The input field required to be filled has also been restructured in that regard.
🙏 Thanks again!

2023-04-07 01:02 UTC, Felix45 requested changes
Hi @SamuelTakyiBoateng , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966" />

 ## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] GitHub flow is used correctly :white_check_mark:  
- [x] Repository has a professional readme file :white_check_mark:  
- [x] Implemented some of the changes from the previous reviewer :white_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 01:20 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @SamuelTakyiBoateng 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 01:20 UTC, tresorsawasawa commented on index.html
> +                <textarea id="opinion" name="textbox" rows="6" cols="40" maxlength="500" required >Write me something...</textarea>
- [ **OPTIONAL** ] To match the your chosen design, I think it would be better if you use the `Write your message here...` text in a `placeholder` attribute instead of being the value of the `textarea` tag. Right now it prevents users to write their messages correctly as they are required to delete it before they write their own messages
```HTML
<textarea id="opinion" .... maxlength="500" required placeholder="Write your message here..."></textarea>
```

2023-04-07 01:31 UTC, merged